server:
  port: 8080
spring:
  application:
    name: codeorbit-ai-backend
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
